---
- name: Create swap space
  sudo: yes
  command: dd if=/dev/zero of=/extraswap bs=1M count=512
  when: ansible_swaptotal_mb < 1

- name: Make swap
  sudo: yes
  command: mkswap /extraswap
  when: ansible_swaptotal_mb < 1

- name: Add to fstab
  sudo: yes
  action: lineinfile dest=/etc/fstab regexp="extraswap" line="/extraswap none swap sw 0 0" state=present

- name: Turn swap on
  sudo: yes
  command: swapon -a

- name: Set swapiness
  sudo: yes
  shell: echo 0 | tee /proc/sys/vm/swappiness