---

- name: Install minimal X11 Environment with Openbox
  sudo: yes
  apt: name={{ item }} state=present
  with_items:
    - xorg
    - lightdm
    - openbox
    - linuxvnc

- name: Set openbox as default session
  sudo: yes
  copy: src=conf/lightdm/10-openbox.conf dest=/usr/share/lightdm/lightdm.conf.d/10-openbox.conf owner=root group=root mode=0644